extends: default
rules:
  line-length:
    max: 200
    level: warning
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
    check-keys: false
  document-start: disable
  indentation:
    spaces: 2
    indent-sequences: consistent
ignore: |
  tests/fixtures/
  tests/shell/golden/
