# .github/workflows/caller-lint-rust-happy.yml
name: caller-lint-rust-happy
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/lint-rust.yml'
      - '.github/workflows/caller-lint-rust-happy.yml'
      - 'tests/fixtures/lint-test/rust-happy/**'

jobs:
  lint:
    uses: ./.github/workflows/lint-rust.yml
    secrets: inherit
    with:
      working_directory: tests/fixtures/lint-test/rust-happy
